services:
  - docker
language: generic
env:
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO="ros"
    - ROS_DISTRO="kinetic" ROS_REPO="ros-shadow-fixed"
    - ROS_DISTRO="kinetic" ROS_REPO="ros"
    - ROS_DISTRO="melodic" ROS_REPO="ros-shadow-fixed"
    - ROS_DISTRO="melodic" ROS_REPO="ros"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh

